---
source: /data/projects/tools/backup-script/test-source
target: /data/projects/tools/backup-script/test-target
---
source: /data/projects/tools/backup-script/test-source
target: /data/projects/tools/backup-script/test-target2
archive: True
max-history: 5